/**
 * Database-query Worker template.
 *
 * Generates a Worker that exposes a single `worker.tool()` reading from
 * (and optionally writing to) a Notion database. The handler returns a
 * STRUCTURED RESULT — never throws — so callers can branch on
 * `result.ok` without wrapping in try/catch.
 *
 * Why one tool per template (not multiple): the pattern definition in
 * PLAN.md §IV.2 maps 1:1. Forge composes multi-step behavior via the
 * `multi-step` template, not by stuffing extra tools here.
 */

import type { JSchemaSpec, ProviderName } from '../types.js';
import {
  describeAsJsdoc,
  renderEnvSetupComment,
  renderImports,
  renderSchema,
  tsString,
} from './shared.js';

export interface DatabaseQueryTemplateArgs {
  workerName: string;
  description: string;
  inputSchema: JSchemaSpec;
  outputSchema: JSchemaSpec;
  requiredOAuth: readonly ProviderName[];
  /**
   * When present, the template imports the matching @forge/connectors factory.
   * Optional because pure-Notion queries don't need a third-party connector.
   */
  connectorImport?: ProviderName;
}

export function databaseQueryTemplate(args: DatabaseQueryTemplateArgs): string {
  const oauth = mergeOauth(args.requiredOAuth, args.connectorImport);
  const imports = renderImports({
    includeNotionClient: true,
    requiredOAuth: oauth,
  });
  const envComment = renderEnvSetupComment({
    workerName: args.workerName,
    connectorBindings: imports.connectorBindings,
    notionEnvVar: 'NOTION_API_KEY',
  });

  const connectorSetup = imports.connectorBindings
    .map(
      (b) =>
        `const ${b.client} = ${b.factory}({ apiKey: process.env[${tsString(b.envVar)}] ?? '' });`,
    )
    .join('\n');

  return `/**
 * ${describeAsJsdoc(args.description)}
 *
 * Pattern: database-query
 * Generated by Forge — do not edit by hand.
 */
${imports.source}

${envComment}

const notion = new NotionClient({ auth: process.env['NOTION_API_KEY'] ?? '' });
${connectorSetup}

worker.tool({
  name: ${tsString(args.workerName)},
  description: ${tsString(args.description)},
  input: ${renderSchema(args.inputSchema)},
  output: ${renderSchema(args.outputSchema)},
  async handler(input) {
    try {
      const dbId = (input as { databaseId?: string }).databaseId ?? process.env['NOTION_DATABASE_ID'] ?? '';
      if (dbId.length === 0) {
        return { ok: false as const, error: 'NOTION_DATABASE_ID missing' };
      }
      const response = await notion.databases.query({
        database_id: dbId,
        page_size: 100,
      });
      return { ok: true as const, results: response.results, nextCursor: response.next_cursor };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return { ok: false as const, error: message };
    }
  },
});
`;
}

function mergeOauth(
  required: readonly ProviderName[],
  extra: ProviderName | undefined,
): readonly ProviderName[] {
  if (!extra) return required;
  if (required.includes(extra)) return required;
  return [...required, extra];
}
