/**
 * External-API-call Worker template.
 *
 * Generates a Worker exposing one `worker.tool()` that calls a third-party
 * connector method and returns the parsed result. No Notion write — this
 * pattern is for read-side enrichments (e.g. "look up a GitHub repo").
 *
 * Notion client import is omitted to keep the bundle minimal.
 */

import type { JSchemaSpec, ProviderName } from '../types.js';
import {
  describeAsJsdoc,
  renderEnvSetupComment,
  renderImports,
  renderSchema,
  tsString,
} from './shared.js';

export interface ExternalApiCallTemplateArgs {
  workerName: string;
  description: string;
  inputSchema: JSchemaSpec;
  outputSchema: JSchemaSpec;
  requiredOAuth: readonly ProviderName[];
  /** Provider whose client makes the outbound call. */
  connectorImport?: ProviderName;
}

export function externalApiCallTemplate(args: ExternalApiCallTemplateArgs): string {
  const oauth = mergeOauth(args.requiredOAuth, args.connectorImport);
  const imports = renderImports({
    includeNotionClient: false,
    requiredOAuth: oauth,
  });
  const envComment = renderEnvSetupComment({
    workerName: args.workerName,
    connectorBindings: imports.connectorBindings,
    notionEnvVar: null,
  });
  const connectorSetup = imports.connectorBindings
    .map(
      (b) =>
        `const ${b.client} = ${b.factory}({ apiKey: process.env[${tsString(b.envVar)}] ?? '' });`,
    )
    .join('\n');
  const primaryClient = imports.connectorBindings[0]?.client ?? null;

  return `/**
 * ${describeAsJsdoc(args.description)}
 *
 * Pattern: external-api-call
 * Generated by Forge — do not edit by hand.
 */
${imports.source}

${envComment}

${connectorSetup}

worker.tool({
  name: ${tsString(args.workerName)},
  description: ${tsString(args.description)},
  input: ${renderSchema(args.inputSchema)},
  output: ${renderSchema(args.outputSchema)},
  async handler(input) {
    ${
      primaryClient === null
        ? `// No connector bound — return the input passthrough.
    return { ok: true as const, result: input };`
        : `try {
      // The connector's method is invoked here; the deployed Worker uses
      // whichever named method maps to the user's request (e.g.
      // ${primaryClient}.getRepo, ${primaryClient}.listIssues, …).
      const result = await invokeConnector(${primaryClient}, input);
      return { ok: true as const, result };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return { ok: false as const, error: message };
    }`
    }
  },
});

${
  primaryClient === null
    ? ``
    : `async function invokeConnector(_client: unknown, input: unknown): Promise<unknown> {
  // Stub: the deployed Worker rewrites this against the specific method.
  return input;
}`
}
`;
}

function mergeOauth(
  required: readonly ProviderName[],
  extra: ProviderName | undefined,
): readonly ProviderName[] {
  if (!extra) return required;
  if (required.includes(extra)) return required;
  return [...required, extra];
}
