/**
 * Multi-step Worker template.
 *
 * Generates a Worker exposing a single `worker.tool()` that chains TWO or
 * THREE operations sequentially (PLAN.md §IV.2 caps at 3 steps). The
 * handler returns the per-step trace so the user can debug which leg
 * failed without reaching into provider logs.
 *
 * The template imports Notion + every provider listed in `requiredOAuth`
 * so the body has all the clients on hand. The step bodies are placeholders
 * the deployed Worker tailors to the user's actual chain.
 */

import type { JSchemaSpec, ProviderName } from '../types.js';
import {
  describeAsJsdoc,
  renderEnvSetupComment,
  renderImports,
  renderSchema,
  tsString,
} from './shared.js';

export interface MultiStepTemplateArgs {
  workerName: string;
  description: string;
  inputSchema: JSchemaSpec;
  outputSchema: JSchemaSpec;
  requiredOAuth: readonly ProviderName[];
  /**
   * Optional ADDITIONAL provider to splice into the connector list. Most
   * multi-step agents already declare their providers in `requiredOAuth`;
   * `connectorImport` is for the edge case where the model's draft only
   * named one and the chain needs another.
   */
  connectorImport?: ProviderName;
}

export function multiStepTemplate(args: MultiStepTemplateArgs): string {
  const oauth = mergeOauth(args.requiredOAuth, args.connectorImport);
  const imports = renderImports({
    includeNotionClient: true,
    requiredOAuth: oauth,
  });
  const envComment = renderEnvSetupComment({
    workerName: args.workerName,
    connectorBindings: imports.connectorBindings,
    notionEnvVar: 'NOTION_API_KEY',
  });
  const connectorSetup = imports.connectorBindings
    .map(
      (b) =>
        `const ${b.client} = ${b.factory}({ apiKey: process.env[${tsString(b.envVar)}] ?? '' });`,
    )
    .join('\n');
  // Reference every client at least once so unused-import lint stays quiet
  // in the generated code without us emitting noisy `_ = client` lines.
  const clientRefs =
    imports.connectorBindings.length > 0
      ? `void (() => [${imports.connectorBindings.map((b) => b.client).join(', ')}])();`
      : `// no third-party connectors required`;

  return `/**
 * ${describeAsJsdoc(args.description)}
 *
 * Pattern: multi-step
 * Generated by Forge — do not edit by hand.
 */
${imports.source}

${envComment}

const notion = new NotionClient({ auth: process.env['NOTION_API_KEY'] ?? '' });
${connectorSetup}

${clientRefs}

worker.tool({
  name: ${tsString(args.workerName)},
  description: ${tsString(args.description)},
  input: ${renderSchema(args.inputSchema)},
  output: ${renderSchema(args.outputSchema)},
  async handler(input) {
    const steps: Array<{ name: string; ok: boolean; durationMs: number; error?: string }> = [];
    const t0 = Date.now();
    try {
      const step1 = await runStep('read-context', async () => {
        return { input };
      });
      steps.push(step1.trace);

      const step2 = await runStep('enrich', async () => {
        return { enriched: step1.result };
      });
      steps.push(step2.trace);

      const step3 = await runStep('write-notion', async () => {
        const dbId = process.env['NOTION_DATABASE_ID'] ?? '';
        if (dbId.length === 0) throw new Error('NOTION_DATABASE_ID missing');
        await notion.pages.create({
          parent: { database_id: dbId },
          properties: { Name: { title: [{ text: { content: 'multi-step result' } }] } } as never,
        });
        return { wrote: true };
      });
      steps.push(step3.trace);

      return {
        ok: true as const,
        steps,
        result: step3.result,
        totalMs: Date.now() - t0,
      };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return {
        ok: false as const,
        steps,
        error: message,
        totalMs: Date.now() - t0,
      };
    }
  },
});

async function runStep<T>(
  name: string,
  body: () => Promise<T>,
): Promise<{ result: T; trace: { name: string; ok: boolean; durationMs: number; error?: string } }> {
  const started = Date.now();
  try {
    const result = await body();
    return { result, trace: { name, ok: true, durationMs: Date.now() - started } };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    return Promise.reject(
      Object.assign(new Error(\`step \${name} failed: \${message}\`), {
        trace: { name, ok: false, durationMs: Date.now() - started, error: message },
      }),
    );
  }
}
`;
}

function mergeOauth(
  required: readonly ProviderName[],
  extra: ProviderName | undefined,
): readonly ProviderName[] {
  if (!extra) return required;
  if (required.includes(extra)) return required;
  return [...required, extra];
}
