/**
 * Sync-source Worker template.
 *
 * Generates a Worker that exposes a `worker.sync()` handler. The runtime
 * invokes the handler on a schedule with the previous cursor; the handler
 * pulls fresh rows from the external API (via the connector) and upserts
 * them into a Notion database, returning the next cursor.
 *
 * Templates keep the cursor opaque (string|null) because Notion's poll
 * scheduler hands us back whatever we returned last.
 */

import type { JSchemaSpec, ProviderName } from '../types.js';
import {
  describeAsJsdoc,
  renderEnvSetupComment,
  renderImports,
  renderSchema,
  tsString,
} from './shared.js';

export interface SyncSourceTemplateArgs {
  workerName: string;
  description: string;
  inputSchema: JSchemaSpec;
  outputSchema: JSchemaSpec;
  requiredOAuth: readonly ProviderName[];
  /** Provider whose client drives the upstream pull. */
  connectorImport?: ProviderName;
}

export function syncSourceTemplate(args: SyncSourceTemplateArgs): string {
  const oauth = mergeOauth(args.requiredOAuth, args.connectorImport);
  const imports = renderImports({
    includeNotionClient: true,
    requiredOAuth: oauth,
  });
  const envComment = renderEnvSetupComment({
    workerName: args.workerName,
    connectorBindings: imports.connectorBindings,
    notionEnvVar: 'NOTION_API_KEY',
  });
  const connectorSetup = imports.connectorBindings
    .map(
      (b) =>
        `const ${b.client} = ${b.factory}({ apiKey: process.env[${tsString(b.envVar)}] ?? '' });`,
    )
    .join('\n');
  // The primary client identifier — first connector in the list — drives the
  // upstream pull. If no connectors are bound (rare for sync-source), the
  // handler degrades to a "nothing to sync" no-op.
  const primaryClient = imports.connectorBindings[0]?.client ?? null;

  return `/**
 * ${describeAsJsdoc(args.description)}
 *
 * Pattern: sync-source
 * Generated by Forge — do not edit by hand.
 */
${imports.source}

${envComment}

const notion = new NotionClient({ auth: process.env['NOTION_API_KEY'] ?? '' });
${connectorSetup}

worker.sync({
  name: ${tsString(args.workerName)},
  description: ${tsString(args.description)},
  input: ${renderSchema(args.inputSchema)},
  output: ${renderSchema(args.outputSchema)},
  async handler(_input, ctx: { cursor: string | null }) {
    const dbId = process.env['NOTION_DATABASE_ID'] ?? '';
    if (dbId.length === 0) {
      return { ok: false as const, error: 'NOTION_DATABASE_ID missing', cursor: ctx.cursor };
    }
    ${
      primaryClient === null
        ? `// No upstream connector bound — emit empty page and keep cursor.
    return { ok: true as const, upserted: 0, cursor: ctx.cursor };`
        : `try {
      // Replace 'fetchPage' with the concrete connector method for the
      // upstream you're syncing (e.g. vercel.listDeployments, sentry.listIssues).
      const page = await fetchPage(${primaryClient}, ctx.cursor);
      let upserted = 0;
      for (const row of page.items) {
        await notion.pages.create({
          parent: { database_id: dbId },
          properties: rowToProperties(row) as never,
        });
        upserted += 1;
      }
      return { ok: true as const, upserted, cursor: page.nextCursor };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return { ok: false as const, error: message, cursor: ctx.cursor };
    }`
    }
  },
});

${
  primaryClient === null
    ? ``
    : `interface UpstreamRow { id: string; updatedAt?: string }
interface UpstreamPage { items: UpstreamRow[]; nextCursor: string | null }

async function fetchPage(_client: unknown, _cursor: string | null): Promise<UpstreamPage> {
  // Stub: the deployed Worker rewrites this against the real connector.
  return { items: [], nextCursor: null };
}

function rowToProperties(row: UpstreamRow): Record<string, unknown> {
  return {
    Name: {
      title: [{ text: { content: row.id } }],
    },
  };
}`
}
`;
}

function mergeOauth(
  required: readonly ProviderName[],
  extra: ProviderName | undefined,
): readonly ProviderName[] {
  if (!extra) return required;
  if (required.includes(extra)) return required;
  return [...required, extra];
}
