/**
 * Webhook-trigger Worker template.
 *
 * Generates a Worker that exposes a `worker.webhook()` endpoint. The handler
 * receives the inbound payload, validates it against `inputSchema`, calls
 * the configured external connector if one is bound, then upserts into a
 * Notion database.
 *
 * Webhook handlers return a result object so retries from the provider can
 * be acknowledged (or rejected) without needing a thrown error to cross the
 * runtime boundary.
 */

import type { JSchemaSpec, ProviderName } from '../types.js';
import {
  describeAsJsdoc,
  renderEnvSetupComment,
  renderImports,
  renderSchema,
  tsString,
} from './shared.js';

export interface WebhookTriggerTemplateArgs {
  workerName: string;
  description: string;
  inputSchema: JSchemaSpec;
  outputSchema: JSchemaSpec;
  requiredOAuth: readonly ProviderName[];
  /** Provider for the connector to import (e.g. github, stripe). */
  connectorImport?: ProviderName;
}

export function webhookTriggerTemplate(args: WebhookTriggerTemplateArgs): string {
  const oauth = mergeOauth(args.requiredOAuth, args.connectorImport);
  const imports = renderImports({
    includeNotionClient: true,
    requiredOAuth: oauth,
  });
  const envComment = renderEnvSetupComment({
    workerName: args.workerName,
    connectorBindings: imports.connectorBindings,
    notionEnvVar: 'NOTION_API_KEY',
  });
  const connectorSetup = imports.connectorBindings
    .map(
      (b) =>
        `const ${b.client} = ${b.factory}({ apiKey: process.env[${tsString(b.envVar)}] ?? '' });`,
    )
    .join('\n');
  const connectorRefs = imports.connectorBindings.map((b) => b.client).join(', ') || '/* no providers */';

  return `/**
 * ${describeAsJsdoc(args.description)}
 *
 * Pattern: webhook-trigger
 * Generated by Forge — do not edit by hand.
 */
${imports.source}

${envComment}

const notion = new NotionClient({ auth: process.env['NOTION_API_KEY'] ?? '' });
${connectorSetup}

void ${connectorRefs.startsWith('/*') ? "(() => undefined)()" : `(() => [${connectorRefs}])()`};

worker.webhook({
  name: ${tsString(args.workerName)},
  description: ${tsString(args.description)},
  input: ${renderSchema(args.inputSchema)},
  output: ${renderSchema(args.outputSchema)},
  async handler(event) {
    try {
      const dbId = process.env['NOTION_DATABASE_ID'] ?? '';
      if (dbId.length === 0) {
        return { ok: false as const, error: 'NOTION_DATABASE_ID missing' };
      }
      const properties: Record<string, unknown> = {
        Name: {
          title: [
            { text: { content: typeof (event as { id?: unknown }).id === 'string' ? String((event as { id: string }).id) : 'event' } },
          ],
        },
      };
      const created = await notion.pages.create({
        parent: { database_id: dbId },
        properties: properties as never,
      });
      return { ok: true as const, pageId: created.id };
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      return { ok: false as const, error: message };
    }
  },
});
`;
}

function mergeOauth(
  required: readonly ProviderName[],
  extra: ProviderName | undefined,
): readonly ProviderName[] {
  if (!extra) return required;
  if (required.includes(extra)) return required;
  return [...required, extra];
}
